/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.intellimate.server.database.model.IzouServer;
import org.intellimate.server.database.model.Keys;
import org.intellimate.server.database.model.tables.records.AppDependencyRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppDependency extends TableImpl<AppDependencyRecord> {

	private static final long serialVersionUID = 849625331;

	/**
	 * The reference instance of <code>izou_server.App_Dependency</code>
	 */
	public static final AppDependency APP_DEPENDENCY = new AppDependency();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<AppDependencyRecord> getRecordType() {
		return AppDependencyRecord.class;
	}

	/**
	 * The column <code>izou_server.App_Dependency.id_App_Dependency</code>.
	 */
	public final TableField<AppDependencyRecord, Integer> ID_APP_DEPENDENCY = createField("id_App_Dependency", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>izou_server.App_Dependency.subject</code>.
	 */
	public final TableField<AppDependencyRecord, Integer> SUBJECT = createField("subject", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>izou_server.App_Dependency.dependency</code>.
	 */
	public final TableField<AppDependencyRecord, Integer> DEPENDENCY = createField("dependency", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>izou_server.App_Dependency</code> table reference
	 */
	public AppDependency() {
		this("App_Dependency", null);
	}

	/**
	 * Create an aliased <code>izou_server.App_Dependency</code> table reference
	 */
	public AppDependency(String alias) {
		this(alias, APP_DEPENDENCY);
	}

	private AppDependency(String alias, Table<AppDependencyRecord> aliased) {
		this(alias, aliased, null);
	}

	private AppDependency(String alias, Table<AppDependencyRecord> aliased, Field<?>[] parameters) {
		super(alias, IzouServer.IZOU_SERVER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<AppDependencyRecord> getPrimaryKey() {
		return Keys.KEY_APP_DEPENDENCY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<AppDependencyRecord>> getKeys() {
		return Arrays.<UniqueKey<AppDependencyRecord>>asList(Keys.KEY_APP_DEPENDENCY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<AppDependencyRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<AppDependencyRecord, ?>>asList(Keys.APP_DEPENDENCY_SUBJECT, Keys.APP_DEPENDENCY_DEPENDENCY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppDependency as(String alias) {
		return new AppDependency(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AppDependency rename(String name) {
		return new AppDependency(name, null);
	}
}
