/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.intellimate.server.database.model.Izoudb;
import org.intellimate.server.database.model.Keys;
import org.intellimate.server.database.model.tables.records.AppTagRecord;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppTag extends TableImpl<AppTagRecord> {

    private static final long serialVersionUID = 1515245222;

    /**
     * The reference instance of <code>izoudb.App_Tag</code>
     */
    public static final AppTag APP_TAG = new AppTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AppTagRecord> getRecordType() {
        return AppTagRecord.class;
    }

    /**
     * The column <code>izoudb.App_Tag.id_App_Tags</code>.
     */
    public final TableField<AppTagRecord, Integer> ID_APP_TAGS = createField("id_App_Tags", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>izoudb.App_Tag.name</code>.
     */
    public final TableField<AppTagRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * Create a <code>izoudb.App_Tag</code> table reference
     */
    public AppTag() {
        this("App_Tag", null);
    }

    /**
     * Create an aliased <code>izoudb.App_Tag</code> table reference
     */
    public AppTag(String alias) {
        this(alias, APP_TAG);
    }

    private AppTag(String alias, Table<AppTagRecord> aliased) {
        this(alias, aliased, null);
    }

    private AppTag(String alias, Table<AppTagRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Izoudb.IZOUDB;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AppTagRecord, Integer> getIdentity() {
        return Keys.IDENTITY_APP_TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AppTagRecord> getPrimaryKey() {
        return Keys.KEY_APP_TAG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AppTagRecord>> getKeys() {
        return Arrays.<UniqueKey<AppTagRecord>>asList(Keys.KEY_APP_TAG_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppTag as(String alias) {
        return new AppTag(alias, this);
    }

    /**
     * Rename this table
     */
    public AppTag rename(String name) {
        return new AppTag(name, null);
    }
}
