/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.intellimate.server.database.model.IzouServer;
import org.intellimate.server.database.model.Keys;
import org.intellimate.server.database.model.tables.records.IzouRecord;
import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Izou extends TableImpl<IzouRecord> {

	private static final long serialVersionUID = 1886091042;

	/**
	 * The reference instance of <code>izou_server.Izou</code>
	 */
	public static final Izou IZOU = new Izou();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<IzouRecord> getRecordType() {
		return IzouRecord.class;
	}

	/**
	 * The column <code>izou_server.Izou.id_Izou</code>.
	 */
	public final TableField<IzouRecord, Integer> ID_IZOU = createField("id_Izou", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>izou_server.Izou.version</code>.
	 */
	public final TableField<IzouRecord, Integer> VERSION = createField("version", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>izou_server.Izou</code> table reference
	 */
	public Izou() {
		this("Izou", null);
	}

	/**
	 * Create an aliased <code>izou_server.Izou</code> table reference
	 */
	public Izou(String alias) {
		this(alias, IZOU);
	}

	private Izou(String alias, Table<IzouRecord> aliased) {
		this(alias, aliased, null);
	}

	private Izou(String alias, Table<IzouRecord> aliased, Field<?>[] parameters) {
		super(alias, IzouServer.IZOU_SERVER, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<IzouRecord> getPrimaryKey() {
		return Keys.KEY_IZOU_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<IzouRecord>> getKeys() {
		return Arrays.<UniqueKey<IzouRecord>>asList(Keys.KEY_IZOU_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Izou as(String alias) {
		return new Izou(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Izou rename(String name) {
		return new Izou(name, null);
	}
}
