/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.intellimate.server.database.model.tables.App;
import org.intellimate.server.database.model.tables.AppActiveTag;
import org.intellimate.server.database.model.tables.AppDependency;
import org.intellimate.server.database.model.tables.AppInstance;
import org.intellimate.server.database.model.tables.AppTag;
import org.intellimate.server.database.model.tables.AppVersion;
import org.intellimate.server.database.model.tables.DatabaseVersion;
import org.intellimate.server.database.model.tables.Izou;
import org.intellimate.server.database.model.tables.IzouInstance;
import org.intellimate.server.database.model.tables.User;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Izoudb extends SchemaImpl {

    private static final long serialVersionUID = 307630979;

    /**
     * The reference instance of <code>izoudb</code>
     */
    public static final Izoudb IZOUDB = new Izoudb();

    /**
     * The table <code>izoudb.App</code>.
     */
    public final App APP = org.intellimate.server.database.model.tables.App.APP;

    /**
     * The table <code>izoudb.App_Active_Tag</code>.
     */
    public final AppActiveTag APP_ACTIVE_TAG = org.intellimate.server.database.model.tables.AppActiveTag.APP_ACTIVE_TAG;

    /**
     * The table <code>izoudb.App_Dependency</code>.
     */
    public final AppDependency APP_DEPENDENCY = org.intellimate.server.database.model.tables.AppDependency.APP_DEPENDENCY;

    /**
     * The table <code>izoudb.App_Instance</code>.
     */
    public final AppInstance APP_INSTANCE = org.intellimate.server.database.model.tables.AppInstance.APP_INSTANCE;

    /**
     * The table <code>izoudb.App_Tag</code>.
     */
    public final AppTag APP_TAG = org.intellimate.server.database.model.tables.AppTag.APP_TAG;

    /**
     * The table <code>izoudb.App_Version</code>.
     */
    public final AppVersion APP_VERSION = org.intellimate.server.database.model.tables.AppVersion.APP_VERSION;

    /**
     * The table <code>izoudb.Database_Version</code>.
     */
    public final DatabaseVersion DATABASE_VERSION = org.intellimate.server.database.model.tables.DatabaseVersion.DATABASE_VERSION;

    /**
     * The table <code>izoudb.Izou</code>.
     */
    public final Izou IZOU = org.intellimate.server.database.model.tables.Izou.IZOU;

    /**
     * The table <code>izoudb.Izou_Instance</code>.
     */
    public final IzouInstance IZOU_INSTANCE = org.intellimate.server.database.model.tables.IzouInstance.IZOU_INSTANCE;

    /**
     * The table <code>izoudb.User</code>.
     */
    public final User USER = org.intellimate.server.database.model.tables.User.USER;

    /**
     * No further instances allowed
     */
    private Izoudb() {
        super("izoudb", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            App.APP,
            AppActiveTag.APP_ACTIVE_TAG,
            AppDependency.APP_DEPENDENCY,
            AppInstance.APP_INSTANCE,
            AppTag.APP_TAG,
            AppVersion.APP_VERSION,
            DatabaseVersion.DATABASE_VERSION,
            Izou.IZOU,
            IzouInstance.IZOU_INSTANCE,
            User.USER);
    }
}
