/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.intellimate.server.database.model.tables.App;
import org.intellimate.server.database.model.tables.AppActiveTag;
import org.intellimate.server.database.model.tables.AppDependency;
import org.intellimate.server.database.model.tables.AppInstance;
import org.intellimate.server.database.model.tables.AppTag;
import org.intellimate.server.database.model.tables.AppVersion;
import org.intellimate.server.database.model.tables.IzouInstance;
import org.intellimate.server.database.model.tables.User;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IzouServer extends SchemaImpl {

	private static final long serialVersionUID = 1243862958;

	/**
	 * The reference instance of <code>izou_server</code>
	 */
	public static final IzouServer IZOU_SERVER = new IzouServer();

	/**
	 * No further instances allowed
	 */
	private IzouServer() {
		super("izou_server");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			App.APP,
			AppActiveTag.APP_ACTIVE_TAG,
			AppDependency.APP_DEPENDENCY,
			AppInstance.APP_INSTANCE,
			AppTag.APP_TAG,
			AppVersion.APP_VERSION,
			IzouInstance.IZOU_INSTANCE,
			User.USER);
	}
}
