-- MySQL Script generated by MySQL Workbench
-- Sat May 28 20:44:27 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- -----------------------------------------------------
-- Schema izoudb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema izoudb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `izoudb` DEFAULT CHARACTER SET utf8mb4 ;
USE `izoudb` ;

-- -----------------------------------------------------
-- Table `izoudb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`User` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `root` BIT(1) NOT NULL,
  `confirmed` BIT(1) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`App`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`App` (
  `id_app` INT(11) NOT NULL AUTO_INCREMENT,
  `developer` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NOT NULL,
  `active` BIT(1) NOT NULL,
  `package` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_app`),
  INDEX `developer_idx` (`developer` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `package_UNIQUE` (`package` ASC),
  CONSTRAINT `app_developer`
    FOREIGN KEY (`developer`)
    REFERENCES `izoudb`.`User` (`id_user`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`App_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`App_Tag` (
  `id_App_Tags` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_App_Tags`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`App_Active_Tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`App_Active_Tag` (
  `id_App_Active_Tag` INT(11) NOT NULL AUTO_INCREMENT,
  `app` INT(11) NOT NULL,
  `tag` INT(11) NOT NULL,
  PRIMARY KEY (`id_App_Active_Tag`),
  INDEX `app_active_tag_app_ref_idx` (`app` ASC),
  INDEX `app_active_tag_tag_ref_idx` (`tag` ASC),
  CONSTRAINT `app_active_tag_app_ref`
    FOREIGN KEY (`app`)
    REFERENCES `izoudb`.`App` (`id_app`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `app_active_tag_tag_ref`
    FOREIGN KEY (`tag`)
    REFERENCES `izoudb`.`App_Tag` (`id_App_Tags`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`App_Version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`App_Version` (
  `id_App_Version` INT(11) NOT NULL AUTO_INCREMENT,
  `app` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `major` INT(11) NOT NULL,
  `minor` INT(11) NOT NULL,
  `patch` INT(11) NOT NULL,
  PRIMARY KEY (`id_App_Version`),
  INDEX `versioned_app_idx` (`app` ASC),
  CONSTRAINT `versioned_app`
    FOREIGN KEY (`app`)
    REFERENCES `izoudb`.`App` (`id_app`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`App_Instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`App_Instance` (
  `id_App_Instance` INT(11) NOT NULL AUTO_INCREMENT,
  `app_reference` INT(11) NOT NULL,
  `platform` VARCHAR(255) NOT NULL,
  `active` BIT(1) NOT NULL,
  `error` VARCHAR(255) NULL,
  PRIMARY KEY (`id_App_Instance`),
  INDEX `app_instance_ref_idx` (`app_reference` ASC),
  CONSTRAINT `app_instance_ref`
    FOREIGN KEY (`app_reference`)
    REFERENCES `izoudb`.`App_Version` (`id_App_Version`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`App_Dependency`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`App_Dependency` (
  `id_App_Dependency` INT(11) NOT NULL AUTO_INCREMENT,
  `subject` INT(11) NOT NULL,
  `dependency` INT(11) NOT NULL,
  PRIMARY KEY (`id_App_Dependency`),
  INDEX `app_dependency_subject_idx` (`subject` ASC),
  INDEX `app_dependency_dependency_idx` (`dependency` ASC),
  CONSTRAINT `app_dependency_dependency`
    FOREIGN KEY (`dependency`)
    REFERENCES `izoudb`.`App` (`id_app`)
    ON UPDATE CASCADE,
  CONSTRAINT `app_dependency_subject`
    FOREIGN KEY (`subject`)
    REFERENCES `izoudb`.`App_Instance` (`id_App_Instance`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`Database_Version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`Database_Version` (
  `id_Database_Version` INT(11) NOT NULL AUTO_INCREMENT,
  `version` INT(11) NOT NULL,
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_Database_Version`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`Izou`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`Izou` (
  `id_Izou` INT(11) NOT NULL AUTO_INCREMENT,
  `active` BIT(1) NOT NULL,
  `major` INT(11) NOT NULL,
  `minor` INT(11) NOT NULL,
  `patch` INT(11) NOT NULL,
  `version` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Izou`),
  UNIQUE INDEX `version_UNIQUE` (`version` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `izoudb`.`Izou_Instance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `izoudb`.`Izou_Instance` (
  `id_Instances` INT(11) NOT NULL AUTO_INCREMENT,
  `user` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_Instances`),
  INDEX `izou_instance_user_idx` (`user` ASC),
  CONSTRAINT `izou_instance_user`
    FOREIGN KEY (`user`)
    REFERENCES `izoudb`.`User` (`id_user`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;
