/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables.records;


import javax.annotation.Generated;

import org.intellimate.server.database.model.tables.AppActiveTag;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppActiveTagRecord extends UpdatableRecordImpl<AppActiveTagRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -931648264;

    /**
     * Setter for <code>izoudb.App_Active_Tag.id_App_Active_Tag</code>.
     */
    public void setIdAppActiveTag(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>izoudb.App_Active_Tag.id_App_Active_Tag</code>.
     */
    public Integer getIdAppActiveTag() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>izoudb.App_Active_Tag.app</code>.
     */
    public void setApp(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>izoudb.App_Active_Tag.app</code>.
     */
    public Integer getApp() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>izoudb.App_Active_Tag.tag</code>.
     */
    public void setTag(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>izoudb.App_Active_Tag.tag</code>.
     */
    public Integer getTag() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AppActiveTag.APP_ACTIVE_TAG.ID_APP_ACTIVE_TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return AppActiveTag.APP_ACTIVE_TAG.APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return AppActiveTag.APP_ACTIVE_TAG.TAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdAppActiveTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getApp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppActiveTagRecord value1(Integer value) {
        setIdAppActiveTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppActiveTagRecord value2(Integer value) {
        setApp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppActiveTagRecord value3(Integer value) {
        setTag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppActiveTagRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppActiveTagRecord
     */
    public AppActiveTagRecord() {
        super(AppActiveTag.APP_ACTIVE_TAG);
    }

    /**
     * Create a detached, initialised AppActiveTagRecord
     */
    public AppActiveTagRecord(Integer idAppActiveTag, Integer app, Integer tag) {
        super(AppActiveTag.APP_ACTIVE_TAG);

        set(0, idAppActiveTag);
        set(1, app);
        set(2, tag);
    }
}
