/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables.records;


import javax.annotation.Generated;

import org.intellimate.server.database.model.tables.App;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppRecord extends UpdatableRecordImpl<AppRecord> implements Record5<Integer, Integer, String, String, Boolean> {

    private static final long serialVersionUID = 287379675;

    /**
     * Setter for <code>izoudb.App.id_app</code>.
     */
    public void setIdApp(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>izoudb.App.id_app</code>.
     */
    public Integer getIdApp() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>izoudb.App.developer</code>.
     */
    public void setDeveloper(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>izoudb.App.developer</code>.
     */
    public Integer getDeveloper() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>izoudb.App.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>izoudb.App.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>izoudb.App.description</code>.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>izoudb.App.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>izoudb.App.active</code>.
     */
    public void setActive(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>izoudb.App.active</code>.
     */
    public Boolean getActive() {
        return (Boolean) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Boolean> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, String, String, Boolean> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return App.APP.ID_APP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return App.APP.DEVELOPER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return App.APP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return App.APP.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field5() {
        return App.APP.ACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getIdApp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getDeveloper();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value5() {
        return getActive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppRecord value1(Integer value) {
        setIdApp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppRecord value2(Integer value) {
        setDeveloper(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppRecord value4(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppRecord value5(Boolean value) {
        setActive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AppRecord values(Integer value1, Integer value2, String value3, String value4, Boolean value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppRecord
     */
    public AppRecord() {
        super(App.APP);
    }

    /**
     * Create a detached, initialised AppRecord
     */
    public AppRecord(Integer idApp, Integer developer, String name, String description, Boolean active) {
        super(App.APP);

        set(0, idApp);
        set(1, developer);
        set(2, name);
        set(3, description);
        set(4, active);
    }
}
