/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.intellimate.server.database.model.tables.AppVersion;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppVersionRecord extends UpdatableRecordImpl<AppVersionRecord> implements Record4<Integer, Integer, String, Timestamp> {

	private static final long serialVersionUID = 1733259009;

	/**
	 * Setter for <code>izou_server.App_Version.id_App_Version</code>.
	 */
	public void setIdAppVersion(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.id_App_Version</code>.
	 */
	public Integer getIdAppVersion() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>izou_server.App_Version.app</code>.
	 */
	public void setApp(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.app</code>.
	 */
	public Integer getApp() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>izou_server.App_Version.version</code>.
	 */
	public void setVersion(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.version</code>.
	 */
	public String getVersion() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>izou_server.App_Version.timestamp</code>.
	 */
	public void setTimestamp(Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.timestamp</code>.
	 */
	public Timestamp getTimestamp() {
		return (Timestamp) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Timestamp> fieldsRow() {
		return (Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row4<Integer, Integer, String, Timestamp> valuesRow() {
		return (Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AppVersion.APP_VERSION.ID_APP_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AppVersion.APP_VERSION.APP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return AppVersion.APP_VERSION.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return AppVersion.APP_VERSION.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdAppVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getApp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value1(Integer value) {
		setIdAppVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value2(Integer value) {
		setApp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value3(String value) {
		setVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value4(Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord values(Integer value1, Integer value2, String value3, Timestamp value4) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppVersionRecord
	 */
	public AppVersionRecord() {
		super(AppVersion.APP_VERSION);
	}

	/**
	 * Create a detached, initialised AppVersionRecord
	 */
	public AppVersionRecord(Integer idAppVersion, Integer app, String version, Timestamp timestamp) {
		super(AppVersion.APP_VERSION);

		setValue(0, idAppVersion);
		setValue(1, app);
		setValue(2, version);
		setValue(3, timestamp);
	}
}
