/**
 * This class is generated by jOOQ
 */
package org.intellimate.server.database.model.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.intellimate.server.database.model.tables.AppVersion;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppVersionRecord extends UpdatableRecordImpl<AppVersionRecord> implements Record6<Integer, Integer, Timestamp, Integer, Integer, Integer> {

	private static final long serialVersionUID = 1883403373;

	/**
	 * Setter for <code>izou_server.App_Version.id_App_Version</code>.
	 */
	public void setIdAppVersion(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.id_App_Version</code>.
	 */
	public Integer getIdAppVersion() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>izou_server.App_Version.app</code>.
	 */
	public void setApp(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.app</code>.
	 */
	public Integer getApp() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>izou_server.App_Version.timestamp</code>.
	 */
	public void setTimestamp(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.timestamp</code>.
	 */
	public Timestamp getTimestamp() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>izou_server.App_Version.major</code>.
	 */
	public void setMajor(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.major</code>.
	 */
	public Integer getMajor() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>izou_server.App_Version.minor</code>.
	 */
	public void setMinor(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.minor</code>.
	 */
	public Integer getMinor() {
		return (Integer) getValue(4);
	}

	/**
	 * Setter for <code>izou_server.App_Version.patch</code>.
	 */
	public void setPatch(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>izou_server.App_Version.patch</code>.
	 */
	public Integer getPatch() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Timestamp, Integer, Integer, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Timestamp, Integer, Integer, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return AppVersion.APP_VERSION.ID_APP_VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return AppVersion.APP_VERSION.APP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return AppVersion.APP_VERSION.TIMESTAMP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return AppVersion.APP_VERSION.MAJOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return AppVersion.APP_VERSION.MINOR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return AppVersion.APP_VERSION.PATCH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getIdAppVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getApp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getTimestamp();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getMajor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getMinor();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getPatch();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value1(Integer value) {
		setIdAppVersion(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value2(Integer value) {
		setApp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value3(Timestamp value) {
		setTimestamp(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value4(Integer value) {
		setMajor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value5(Integer value) {
		setMinor(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord value6(Integer value) {
		setPatch(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AppVersionRecord values(Integer value1, Integer value2, Timestamp value3, Integer value4, Integer value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AppVersionRecord
	 */
	public AppVersionRecord() {
		super(AppVersion.APP_VERSION);
	}

	/**
	 * Create a detached, initialised AppVersionRecord
	 */
	public AppVersionRecord(Integer idAppVersion, Integer app, Timestamp timestamp, Integer major, Integer minor, Integer patch) {
		super(AppVersion.APP_VERSION);

		setValue(0, idAppVersion);
		setValue(1, app);
		setValue(2, timestamp);
		setValue(3, major);
		setValue(4, minor);
		setValue(5, patch);
	}
}
