version: '2'
services:
  server:
    image: intellimate/server:latest
    environment:
      DOMAIN: http://${DOCKERIP}:4567/
      LOCAL_FILE_DIR: /data/izou
      EMAIL_DISABLED: true

  db_izou:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: izoudb
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    command:
        - --character-set-server=utf8mb4