version: '2'
services:
  server:
    extends:
        file: base.yml
        service: server
    volumes:
      - /data/izou
    links:
       - db_izou:db_izou
    ports:
       - "4567:4567"
       - "4000:4000"

  db_izou:
    extends:
        file: base.yml
        service: db_izou
    command:
        - --character-set-server=utf8mb4
    ports:
         - "3306:3306"