version: '2'
services:
  server:
    extends:
        file: base.yml
        service: server
    links:
       - db_izou:db_izou

  db_izou:
    extends:
        file: base.yml
        service: db_izou
    command:
        - --character-set-server=utf8mb4