// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-protobuf/izou.proto

package org.intellimate.server.proto;

public interface IzouOrBuilder extends
    // @@protoc_insertion_point(interface_extends:intellimate.Izou)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>optional int32 version = 2;</code>
   */
  int getVersion();
}
